### Load excel to dataframe

In [1]:
import pandas as pd
import re

file_path = '/mnt/d/pydatascience/hiv_txp_sr/data/supp.xlsx'

def process_sheet_name(sheet_name):
    # Make lowercase, remove non-alphanumeric characters, replace spaces with '_', and add '_df'
    return re.sub(r'\W+', '', sheet_name.replace(' ', '_').lower()) + '_df'

def detect_header_rows(sheet):
    # Read the first few rows of the sheet
    preview = pd.read_excel(file_path, sheet_name=sheet, nrows=20)  # Adjust the number of rows as needed
    # Find the row index where the marker is located
    marker_indices = preview[preview.iloc[:, 0] == 'DATA_STARTS_HERE'].index
    # Check if the marker is found
    if not marker_indices.empty:
        marker_row_index = marker_indices.max() + 1
        # Return a list of header rows up to the row just before the marker
        return list(range(marker_row_index))
    else:
        # Default to the first row as header if marker not found
        return [0]  # Default to the first row as header if marker not found


xls = pd.ExcelFile(file_path)
sheet_names = xls.sheet_names
created_dataframes = []

for sheet_name in sheet_names:
    header_rows = detect_header_rows(sheet_name)
    df = pd.read_excel(file_path, sheet_name=sheet_name, header=header_rows)
    df = df[df.iloc[:, 0] != 'DATA_STARTS_HERE']

    # Processed name
    processed_name = process_sheet_name(sheet_name)

    # Create DataFrame with dynamic name
    globals()[processed_name] = df
    created_dataframes.append(processed_name)

# Displaying the names of the created DataFrames
print("Created DataFrame names:")
print(created_dataframes)

for df_name in created_dataframes:
    print(f"First few rows of {df_name}:")
    display(globals()[df_name].head())

Created DataFrame names:
['included_paper_df', '1_outcome_df', 'art_related_df', 'hiv_related_df', 'immunosuppressants_df']
First few rows of included_paper_df:

,Study ID,Author,Year of publication,Country of study,Study type,Sample size (HIV seropositive only),Intervention,Outcome,Conclusion,HIV negative samples,Intervention.1,Outcome.1,Conclusion.1,Remarks
1,Abbott2004,Abbott,2004.0,USA,Retrospective cohort study,47.0,NaN,NaN,NaN,27804.0,retrospective cohort analysis of U.S. adult de...,HIV-infected recipients had improved survival ...,kidney transplantation in HIV-infected patient...,"27851 patients from the USRDS database, 47 HIV..."
2,Ailioaie2017,Ailioaie,2017.0,France,Retrospective case-control study,24.0,NaN,NaN,NaN,21.0,retrospectively analyzed data from 24 HIV-infe...,similar incidence of post-transplant infection...,with current antiretroviral therapy and immuno...,24 HIV-infected kidney transplant recipients a...
3,Alfano2018,Alfano,2018.0,Italy,Retrospective Cohort Study,19.0,Kidney transplantation in HIV+ patients,"Patient and graft survival, incidence of acute...",Kidney transplantation was safe and effective ...,200.0,Kidney transplantation in HIV+ patients,"Patient and graft survival, incidence of acute...",Kidney transplantation was safe and effective ...,NaN
4,Alfano2020,Alfano,2020.0,Italy,Retrospective cohort study,22.0,NaN,NaN,NaN,0.0,Comparison of Maraviroc-treated group (10 pati...,Half of the Maraviroc-treated patients dev...,Use of Maraviroc was ineffective in preventing...,NaN
5,Apewokin2018,Apewokin,2018.0,USA,Nationwide analysis using the Inpatient Databa...,605.0,Kidney transplantation in HIV+ patients,"Clinical outcomes, infection rates, rejection ...",Clinical and economic outcomes were comparable...,103532.0,The analysis compared clinical and health care...,The study found that clinical and fiscal outco...,The study concludes that kidney transplantatio...,"104,137 patients (605 HIV-positive)"

First few rows of 1_outcome_df:

  Unnamed: 0_level_0                  Unnamed: 1_level_0   Unnamed: 2_level_0  \
            Study ID Sample size (HIV seropositive only) HIV negative samples
1         Abbott2004                                47.0              27804.0
2       Ailioaie2017                                24.0                 21.0
3         Alfano2018                                19.0                200.0
4         Alfano2020                                22.0                  0.0
5       Apewokin2018                               605.0             103532.0

  In-hospital patient survival (%)        1-year patient survival (%)        \
                              HIV+   HIV-                        HIV+  HIV-
1                              NaN    NaN                         NaN   NaN
2                              NaN    NaN                         NaN   NaN
3                              NaN    NaN                        94.4  98.9
4                              NaN    NaN                         NaN   NaN
5                            99.17  99.44                         NaN   NaN

  3-year patient survival (%)        >= 5-year patient survival (%)  ...  \
                         HIV+   HIV-                           HIV+  ...
1                       95.74  87.17                            NaN  ...
2                         NaN    NaN                          91.67  ...
3                       94.40  95.60                          70.80  ...
4                         NaN    NaN                          63.64  ...
5                         NaN    NaN                            NaN  ...

  3-year cumulative graft rejection (%)  \
                                   HIV-
1                                   NaN
2                                   NaN
3                                   NaN
4                                   NaN
5                                   NaN

  >= 5-year cumulative graft rejection (%)         \
                                      HIV+   HIV-
1                                      NaN    NaN
2                                      NaN    NaN
3                                     48.8    NaN
4                                      NaN    NaN
5                                     27.5  20.75

  1-year infection incidence(100 pt-yr)       \
                                   HIV+ HIV-
1                                   NaN  NaN
2                                   NaN  NaN
3                                   NaN  NaN
4                                   NaN  NaN
5                                   NaN  NaN

  3-year infection incidence(100 pt-yr)       \
                                   HIV+ HIV-
1                                   NaN  NaN
2                                   NaN  NaN
3                                   NaN  NaN
4                                   NaN  NaN
5                                   NaN  NaN

  >= 5-year infection incidence(100 pt-yr)        \
                                      HIV+  HIV-
1                                      NaN   NaN
2                                    24.00  27.0
3                                    26.32   NaN
4                                      NaN   NaN
5                                      NaN   NaN


                                             Remarks
1                                                NaN
2  Overall opportunistic infection RR 1.63, Overa...
3                                                NaN
4                                                NaN
5                  overall infection odds ratio 1.18

[5 rows x 30 columns]

First few rows of art_related_df:

  Unnamed: 0_level_0                  Unnamed: 1_level_0   Unnamed: 2_level_0  \
  Unnamed: 0_level_1                  Unnamed: 1_level_1   Unnamed: 2_level_1
            Study ID Sample size (HIV seropositive only) HIV negative samples
1         Abbott2004                                47.0              27804.0
2       Ailioaie2017                                24.0                 21.0
3         Alfano2018                                19.0                200.0
4         Alfano2020                                22.0                  0.0
5       Apewokin2018                               605.0             103532.0

  Integrase Inhibitor                                                \
           raltegravir         dolutegravir           Total
                Pre-Tx Post-Tx       Pre-Tx Post-Tx  Pre-Tx Post-Tx
1                  NaN     NaN          NaN     NaN     NaN     NaN
2               0.4800  0.6300          NaN     NaN  0.4800  0.6300
3               0.4211  0.7895       0.0526  0.0526  0.4737  0.8421
4               0.7273  0.7273       0.2273  0.2273  0.9545  0.9545
5                  NaN     NaN          NaN     NaN     NaN     NaN

  Protease Inhibitor  ...      NNRTI                         Fusion Inhibitor  \
           Darunavir  ... Nevirapine           Total              Enfuvirtide
              Pre-Tx  ...     Pre-Tx Post-Tx  Pre-Tx Post-Tx           Pre-Tx
1                NaN  ...        NaN     NaN     NaN     NaN              NaN
2                NaN  ...        NaN     NaN  0.3333  0.3333              NaN
3             0.2105  ...        NaN     NaN  0.1579  0.2632           0.1053
4             0.0455  ...        NaN     NaN     NaN     NaN              NaN
5                NaN  ...        NaN     NaN     NaN     NaN              NaN

                          CCR5 Antagonist
            Total               Maraviroc
  Post-Tx  Pre-Tx Post-Tx          Pre-Tx Post-Tx
1     NaN     NaN     NaN             NaN     NaN
2     NaN     NaN     NaN             NaN     NaN
3  0.2105  0.1053  0.2105          0.1579  0.3158
4     NaN     NaN     NaN          0.4545  0.4545
5     NaN     NaN     NaN             NaN     NaN

[5 rows x 59 columns]

First few rows of hiv_related_df:

  Unnamed: 0_level_0                  Unnamed: 1_level_0   Unnamed: 2_level_0  \
            Study ID Sample size (HIV seropositive only) HIV negative samples
1         Abbott2004                                47.0              27804.0
2       Ailioaie2017                                24.0                 21.0
3         Alfano2018                                19.0                200.0
4         Alfano2020                                22.0                  0.0
5       Apewokin2018                               605.0             103532.0

           HIVAN                        CD4 count cells/mm3  \
  Pre-transplant Post-transplant 1 year      Pre-transplant
1            NaN                    NaN                 NaN
2           0.54                    0.0               377.0
3            NaN                    NaN               407.0
4            NaN                    NaN                 NaN
5            NaN                    NaN                 NaN

                         Viral suppression (<= 50copies/mm3)  \
  Post-transplant 1 year                      Pre-transplant
1                    NaN                                 NaN
2                  371.0                                0.88
3                  478.0                                1.00
4                    NaN                                 NaN
5                    NaN                                 NaN


  Post-transplant 1 year Kaposi's sacroma Kaposi's sacroma.1 Remarks
1                    NaN              NaN                NaN     NaN
2                   0.92         0.125000                NaN     NaN
3                   1.00         0.052632                NaN     NaN
4                    NaN              NaN                NaN     NaN
5                    NaN              NaN                NaN     NaN

First few rows of immunosuppressants_df:

  Unnamed: 0_level_0                  Unnamed: 1_level_0   Unnamed: 2_level_0  \
            Study ID Sample size (HIV seropositive only) HIV negative samples
1         Abbott2004                                47.0              27804.0
2       Ailioaie2017                                24.0                 21.0
3         Alfano2018                                19.0                200.0
4         Alfano2020                                22.0                  0.0
5       Apewokin2018                               605.0             103532.0

  Induction                                      Maintainence                \
        ATG      IL-2 Anti-CD52 Others     Total          CNI Mycophenolate
1       NaN       NaN       NaN    NaN  0.468085     1.000000      0.808511
2       NaN  1.000000       NaN    NaN  1.000000     0.960000      0.910000
3       NaN  1.000000       NaN    NaN  1.000000     0.736842      0.157895
4  0.045455  0.909091       NaN    NaN  0.954545     0.818182      0.090909
5       NaN       NaN       NaN    NaN       NaN          NaN           NaN


  Azathioprine Remarks
1     0.148936     NaN
2     0.090000     NaN
3          NaN     NaN
4          NaN     NaN
5          NaN     NaN

### Data cleaning

In [2]:
def clean_column_name(col):
    # Process each element of the header (whether it's a string or a tuple)
    if isinstance(col, tuple):
        return tuple(re.sub(r'\s+', '_', str(c).lower()) for c in col)
    else:
        return re.sub(r'\s+', '_', col.lower())

def clean_column_names(df):
    # Determine the depth of the header
    header_depth = max(len(col) if isinstance(col, tuple) else 1 for col in df.columns)

    # Process each level of the header
    new_columns = []
    for level in range(header_depth):
        level_columns = [
            clean_column_name(col[level] if isinstance(col, tuple) and len(col) > level else col)
            for col in df.columns
        ]
        new_columns.append(level_columns)

    # Reconstruct the multi-level column header
    df.columns = pd.MultiIndex.from_arrays(new_columns)
    return df

for df_name in created_dataframes:
    df = globals()[df_name]
    df = clean_column_names(df)
    globals()[df_name] = df

# Drop columns with all NaN values in each DataFrame
for df_name in created_dataframes:
    df = globals()[df_name]
    # Drop columns where all values are np.nan
    df.dropna(axis=1, how='all', inplace=True)
    # Update the DataFrame in the global namespace
    globals()[df_name] = df

# Displaying the cleaned DataFrames
for df_name in created_dataframes:
    print(f"Cleaned DataFrame '{df_name}':")
    display(globals()[df_name].head())

Cleaned DataFrame 'included_paper_df':

,study_id,author,year_of_publication,country_of_study,study_type,sample_size_(hiv_seropositive_only),intervention,outcome,conclusion,hiv_negative_samples,intervention.1,outcome.1,conclusion.1,remarks
1,Abbott2004,Abbott,2004.0,USA,Retrospective cohort study,47.0,NaN,NaN,NaN,27804.0,retrospective cohort analysis of U.S. adult de...,HIV-infected recipients had improved survival ...,kidney transplantation in HIV-infected patient...,"27851 patients from the USRDS database, 47 HIV..."
2,Ailioaie2017,Ailioaie,2017.0,France,Retrospective case-control study,24.0,NaN,NaN,NaN,21.0,retrospectively analyzed data from 24 HIV-infe...,similar incidence of post-transplant infection...,with current antiretroviral therapy and immuno...,24 HIV-infected kidney transplant recipients a...
3,Alfano2018,Alfano,2018.0,Italy,Retrospective Cohort Study,19.0,Kidney transplantation in HIV+ patients,"Patient and graft survival, incidence of acute...",Kidney transplantation was safe and effective ...,200.0,Kidney transplantation in HIV+ patients,"Patient and graft survival, incidence of acute...",Kidney transplantation was safe and effective ...,NaN
4,Alfano2020,Alfano,2020.0,Italy,Retrospective cohort study,22.0,NaN,NaN,NaN,0.0,Comparison of Maraviroc-treated group (10 pati...,Half of the Maraviroc-treated patients dev...,Use of Maraviroc was ineffective in preventing...,NaN
5,Apewokin2018,Apewokin,2018.0,USA,Nationwide analysis using the Inpatient Databa...,605.0,Kidney transplantation in HIV+ patients,"Clinical outcomes, infection rates, rejection ...",Clinical and economic outcomes were comparable...,103532.0,The analysis compared clinical and health care...,The study found that clinical and fiscal outco...,The study concludes that kidney transplantatio...,"104,137 patients (605 HIV-positive)"

Cleaned DataFrame '1_outcome_df':

  unnamed:_0_level_0                  unnamed:_1_level_0   unnamed:_2_level_0  \
            study_id sample_size_(hiv_seropositive_only) hiv_negative_samples
1         Abbott2004                                47.0              27804.0
2       Ailioaie2017                                24.0                 21.0
3         Alfano2018                                19.0                200.0
4         Alfano2020                                22.0                  0.0
5       Apewokin2018                               605.0             103532.0

  in-hospital_patient_survival_(%)        1-year_patient_survival_(%)        \
                              hiv+   hiv-                        hiv+  hiv-
1                              NaN    NaN                         NaN   NaN
2                              NaN    NaN                         NaN   NaN
3                              NaN    NaN                        94.4  98.9
4                              NaN    NaN                         NaN   NaN
5                            99.17  99.44                         NaN   NaN

  3-year_patient_survival_(%)        >=_5-year_patient_survival_(%)  ...  \
                         hiv+   hiv-                           hiv+  ...
1                       95.74  87.17                            NaN  ...
2                         NaN    NaN                          91.67  ...
3                       94.40  95.60                          70.80  ...
4                         NaN    NaN                          63.64  ...
5                         NaN    NaN                            NaN  ...

  1-year_cumulative_graft_rejection_(%) 3-year_cumulative_graft_rejection_(%)  \
                                   hiv-                                  hiv+
1                                   NaN                                   NaN
2                                   NaN                                   NaN
3                                   NaN                                  40.3
4                                   NaN                                   NaN
5                                   NaN                                   NaN

       >=_5-year_cumulative_graft_rejection_(%)         \
  hiv-                                     hiv+   hiv-
1  NaN                                      NaN    NaN
2  NaN                                      NaN    NaN
3  NaN                                     48.8    NaN
4  NaN                                      NaN    NaN
5  NaN                                     27.5  20.75

  1-year_infection_incidence(100_pt-yr) 3-year_infection_incidence(100_pt-yr)  \
                                   hiv+                                  hiv+
1                                   NaN                                   NaN
2                                   NaN                                   NaN
3                                   NaN                                   NaN
4                                   NaN                                   NaN
5                                   NaN                                   NaN

  >=_5-year_infection_incidence(100_pt-yr)        \
                                      hiv+  hiv-
1                                      NaN   NaN
2                                    24.00  27.0
3                                    26.32   NaN
4                                      NaN   NaN
5                                      NaN   NaN


                                             remarks
1                                                NaN
2  Overall opportunistic infection RR 1.63, Overa...
3                                                NaN
4                                                NaN
5                  overall infection odds ratio 1.18

[5 rows x 28 columns]

Cleaned DataFrame 'art_related_df':

  unnamed:_0_level_0                  unnamed:_1_level_0   unnamed:_2_level_0  \
  unnamed:_0_level_1                  unnamed:_1_level_1   unnamed:_2_level_1
            study_id sample_size_(hiv_seropositive_only) hiv_negative_samples
1         Abbott2004                                47.0              27804.0
2       Ailioaie2017                                24.0                 21.0
3         Alfano2018                                19.0                200.0
4         Alfano2020                                22.0                  0.0
5       Apewokin2018                               605.0             103532.0

  integrase_inhibitor_                                               \
           raltegravir         dolutegravir           total
                pre-tx post-tx       pre-tx post-tx  pre-tx post-tx
1                  NaN     NaN          NaN     NaN     NaN     NaN
2               0.4800  0.6300          NaN     NaN  0.4800  0.6300
3               0.4211  0.7895       0.0526  0.0526  0.4737  0.8421
4               0.7273  0.7273       0.2273  0.2273  0.9545  0.9545
5                  NaN     NaN          NaN     NaN     NaN     NaN

  protease_inhibitor  ...      nnrti                         fusion_inhibitor  \
           darunavir  ... nevirapine           total              enfuvirtide
              pre-tx  ...     pre-tx post-tx  pre-tx post-tx           pre-tx
1                NaN  ...        NaN     NaN     NaN     NaN              NaN
2                NaN  ...        NaN     NaN  0.3333  0.3333              NaN
3             0.2105  ...        NaN     NaN  0.1579  0.2632           0.1053
4             0.0455  ...        NaN     NaN     NaN     NaN              NaN
5                NaN  ...        NaN     NaN     NaN     NaN              NaN

                          ccr5_antagonist
            total               maraviroc
  post-tx  pre-tx post-tx          pre-tx post-tx
1     NaN     NaN     NaN             NaN     NaN
2     NaN     NaN     NaN             NaN     NaN
3  0.2105  0.1053  0.2105          0.1579  0.3158
4     NaN     NaN     NaN          0.4545  0.4545
5     NaN     NaN     NaN             NaN     NaN

[5 rows x 59 columns]

Cleaned DataFrame 'hiv_related_df':

  unnamed:_0_level_0                  unnamed:_1_level_0   unnamed:_2_level_0  \
            study_id sample_size_(hiv_seropositive_only) hiv_negative_samples
1         Abbott2004                                47.0              27804.0
2       Ailioaie2017                                24.0                 21.0
3         Alfano2018                                19.0                200.0
4         Alfano2020                                22.0                  0.0
5       Apewokin2018                               605.0             103532.0

           hivan                        cd4_count_cells/mm3  \
  pre-transplant post-transplant_1_year      pre-transplant
1            NaN                    NaN                 NaN
2           0.54                    0.0               377.0
3            NaN                    NaN               407.0
4            NaN                    NaN                 NaN
5            NaN                    NaN                 NaN

                         viral_suppression_(<=_50copies/mm3)  \
  post-transplant_1_year                      pre-transplant
1                    NaN                                 NaN
2                  371.0                                0.88
3                  478.0                                1.00
4                    NaN                                 NaN
5                    NaN                                 NaN


  post-transplant_1_year kaposi's_sacroma remarks
1                    NaN              NaN     NaN
2                   0.92         0.125000     NaN
3                   1.00         0.052632     NaN
4                    NaN              NaN     NaN
5                    NaN              NaN     NaN

Cleaned DataFrame 'immunosuppressants_df':

  unnamed:_0_level_0                  unnamed:_1_level_0   unnamed:_2_level_0  \
            study_id sample_size_(hiv_seropositive_only) hiv_negative_samples
1         Abbott2004                                47.0              27804.0
2       Ailioaie2017                                24.0                 21.0
3         Alfano2018                                19.0                200.0
4         Alfano2020                                22.0                  0.0
5       Apewokin2018                               605.0             103532.0

  induction                                      maintainence                \
        atg      il-2 anti-cd52 others     total          cni mycophenolate
1       NaN       NaN       NaN    NaN  0.468085     1.000000      0.808511
2       NaN  1.000000       NaN    NaN  1.000000     0.960000      0.910000
3       NaN  1.000000       NaN    NaN  1.000000     0.736842      0.157895
4  0.045455  0.909091       NaN    NaN  0.954545     0.818182      0.090909
5       NaN       NaN       NaN    NaN       NaN          NaN           NaN


  azathioprine remarks
1     0.148936     NaN
2     0.090000     NaN
3          NaN     NaN
4          NaN     NaN
5          NaN     NaN

### Data sanity check

In [3]:
def get_col_id_list(df, column_name='study_id'):
    try:
        # Handle multi-level column headers
        if isinstance(df.columns, pd.MultiIndex):
            # Identify the last level
            last_level = len(df.columns.levels) - 1
            # Extract the column from the last level
            column_data = df.xs(column_name, level=last_level, axis=1)
        else:
            # Single-level headers
            column_data = df[column_name]

        # If the result is a DataFrame, select the first column
        if isinstance(column_data, pd.DataFrame):
            column_data = column_data.iloc[:, 0]

        # Ensure the data is treated as a string and then convert to list
        return column_data.dropna().astype(str).tolist()

    except Exception as e:
        print(f"Error processing column '{column_name}' in DataFrame: {e}")
        return None

study_id_lists = {}
sample_num_lists = {}
control_num_lists = {}

for df_name in created_dataframes:
    df = globals()[df_name]
    study_ids = get_col_id_list(df)
    sample_num = get_col_id_list(df, column_name='sample_size_(hiv_seropositive_only)')
    control_num = get_col_id_list(df, column_name='hiv_negative_samples')
    if study_ids is not None:
        study_id_lists[df_name] = study_ids
        sample_num_lists[df_name] = sample_num
        control_num_lists[df_name] = control_num

# Compare the study_id lists
reference_list = next(iter(study_id_lists.values())) if study_id_lists else None
sanity_check_passed = all(reference_list == study_ids for study_ids in study_id_lists.values())

print("Study_id check result:", sanity_check_passed)

# Compare the sample_size lists
reference_list = next(iter(sample_num_lists.values())) if sample_num_lists else None
sanity_check_passed = all(reference_list == sample_num for sample_num in sample_num_lists.values())

print("Sample_size check result:", sanity_check_passed)

# Compare the control_size lists
reference_list = next(iter(control_num_lists.values())) if control_num_lists else None
sanity_check_passed = all(reference_list == control_num for control_num in control_num_lists.values())

print("Control_size check result:", sanity_check_passed)

Study_id check result: True
Sample_size check result: True
Control_size check result: True

### Merge data

In [4]:
def flatten_headers(df):
    if isinstance(df.columns, pd.MultiIndex):
        # Flatten the column names and remove unwanted prefixes
        df.columns = [
            '_'.join(filter(None, [re.sub(r'^unnamed:_\d+_level_\d+', '', col).strip() 
                                    for col in map(str, col_tuple)]))
            for col_tuple in df.columns.values
        ]
    return df

# Flatten the headers and set 'study_id' as the index for each DataFrame
for df_name in created_dataframes:
    df = globals()[df_name]
    df = flatten_headers(df)

# Start with the first DataFrame as the base
base_df_name = created_dataframes[0]
merged_df = globals()[base_df_name]

# Merge the remaining DataFrames into the base DataFrame
for df_name in created_dataframes[1:]:  # Skip the first DataFrame as it's already the base
    df = globals()[df_name]
    merged_df = pd.merge(merged_df, df, on=['study_id', 'sample_size_(hiv_seropositive_only)', 'hiv_negative_samples'], how='inner')

# Display the merged DataFrame
print("Merged DataFrame:")
display(merged_df.head())

Merged DataFrame:

,study_id,author,year_of_publication,country_of_study,study_type,sample_size_(hiv_seropositive_only),intervention,outcome,conclusion,hiv_negative_samples,...,viral_suppression_(<=_50copies/mm3)_remarks,induction_atg,induction_il-2,induction_anti-cd52,induction_others,induction_total,maintainence_cni,maintainence_mycophenolate,maintainence_azathioprine,maintainence_remarks
0,Abbott2004,Abbott,2004.0,USA,Retrospective cohort study,47.0,NaN,NaN,NaN,27804.0,...,NaN,NaN,NaN,NaN,NaN,0.468085,1.000000,0.808511,0.148936,NaN
1,Ailioaie2017,Ailioaie,2017.0,France,Retrospective case-control study,24.0,NaN,NaN,NaN,21.0,...,NaN,NaN,1.000000,NaN,NaN,1.000000,0.960000,0.910000,0.090000,NaN
2,Alfano2018,Alfano,2018.0,Italy,Retrospective Cohort Study,19.0,Kidney transplantation in HIV+ patients,"Patient and graft survival, incidence of acute...",Kidney transplantation was safe and effective ...,200.0,...,NaN,NaN,1.000000,NaN,NaN,1.000000,0.736842,0.157895,NaN,NaN
3,Alfano2020,Alfano,2020.0,Italy,Retrospective cohort study,22.0,NaN,NaN,NaN,0.0,...,NaN,0.045455,0.909091,NaN,NaN,0.954545,0.818182,0.090909,NaN,NaN
4,Apewokin2018,Apewokin,2018.0,USA,Nationwide analysis using the Inpatient Databa...,605.0,Kidney transplantation in HIV+ patients,"Clinical outcomes, infection rates, rejection ...",Clinical and economic outcomes were comparable...,103532.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Load data to json

In [5]:
merged_df.to_json('/mnt/d/PYDataScience/HIV_TXP_SR/data/supp.json', orient='records', indent=4)